spring:

  main:
    web-application-type: NONE

  datasource:
    url: jdbc:h2:mem:university_db
    username:
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      check-nullability: true